### ISSUE TITLE
Docker For LXC 

### ISSUE THREAD

**Issue by necrose99** [Spike-Pentesting/App-witchcraft#8]
https://github.com/docker/docker

https://github.com/docker/docker
http://stackoverflow.com/questions/22105368/how-docker-is-better-than-vagrantlxcchef
cons yonger product.

pro's Bash (and thus eassier to code  perl to use it ???, ) easier than vagrant in some cases. 

posibly adding support for it might be an item to consider. 

with work and wifi issues been swamped. now i'm doing LanDesk/and "special reserch projects"  might be able to tunnel my Linux VM quietly ..... via vpn..... heheh....

**Comment by mudler** [comment]
https://registry.hub.docker.com/u/sabayon/spinbase-amd64-squashed/
